// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: playerinfo.proto

package Data

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 开始游戏时服务端所需的全部信息
type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid   int32  `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Uid      int32  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetRoomid() int32 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *PlayerInfo) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RoomPlayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllPlayerInfo []*PlayerInfo `protobuf:"bytes,1,rep,name=AllPlayerInfo,proto3" json:"AllPlayerInfo,omitempty"`
	PlayerLen     int32         `protobuf:"varint,2,opt,name=PlayerLen,proto3" json:"PlayerLen,omitempty"`
}

func (x *RoomPlayInfo) Reset() {
	*x = RoomPlayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPlayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayInfo) ProtoMessage() {}

func (x *RoomPlayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayInfo.ProtoReflect.Descriptor instead.
func (*RoomPlayInfo) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{1}
}

func (x *RoomPlayInfo) GetAllPlayerInfo() []*PlayerInfo {
	if x != nil {
		return x.AllPlayerInfo
	}
	return nil
}

func (x *RoomPlayInfo) GetPlayerLen() int32 {
	if x != nil {
		return x.PlayerLen
	}
	return 0
}

type HeroPro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skill       int32   `protobuf:"varint,1,opt,name=skill,proto3" json:"skill,omitempty"`
	Weapon      int32   `protobuf:"varint,2,opt,name=weapon,proto3" json:"weapon,omitempty"`
	HeroLv      int32   `protobuf:"varint,3,opt,name=heroLv,proto3" json:"heroLv,omitempty"`            //英雄等级
	HeroHp      int32   `protobuf:"varint,4,opt,name=heroHp,proto3" json:"heroHp,omitempty"`            //英雄血量
	HeroAtk     int32   `protobuf:"varint,5,opt,name=heroAtk,proto3" json:"heroAtk,omitempty"`          //英雄攻击力
	HeroSpe     int32   `protobuf:"varint,6,opt,name=heroSpe,proto3" json:"heroSpe,omitempty"`          //英雄移速
	HeroDef     int32   `protobuf:"varint,7,opt,name=heroDef,proto3" json:"heroDef,omitempty"`          //英雄防御力
	HeroVector  float64 `protobuf:"fixed64,8,opt,name=heroVector,proto3" json:"heroVector,omitempty"`   //角度
	AttBehavior int32   `protobuf:"varint,9,opt,name=AttBehavior,proto3" json:"AttBehavior,omitempty"`  //攻击行为
	RunBehavior int32   `protobuf:"varint,10,opt,name=RunBehavior,proto3" json:"RunBehavior,omitempty"` //移动行为
	HeroID      int32   `protobuf:"varint,11,opt,name=HeroID,proto3" json:"HeroID,omitempty"`
}

func (x *HeroPro) Reset() {
	*x = HeroPro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroPro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroPro) ProtoMessage() {}

func (x *HeroPro) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroPro.ProtoReflect.Descriptor instead.
func (*HeroPro) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{2}
}

func (x *HeroPro) GetSkill() int32 {
	if x != nil {
		return x.Skill
	}
	return 0
}

func (x *HeroPro) GetWeapon() int32 {
	if x != nil {
		return x.Weapon
	}
	return 0
}

func (x *HeroPro) GetHeroLv() int32 {
	if x != nil {
		return x.HeroLv
	}
	return 0
}

func (x *HeroPro) GetHeroHp() int32 {
	if x != nil {
		return x.HeroHp
	}
	return 0
}

func (x *HeroPro) GetHeroAtk() int32 {
	if x != nil {
		return x.HeroAtk
	}
	return 0
}

func (x *HeroPro) GetHeroSpe() int32 {
	if x != nil {
		return x.HeroSpe
	}
	return 0
}

func (x *HeroPro) GetHeroDef() int32 {
	if x != nil {
		return x.HeroDef
	}
	return 0
}

func (x *HeroPro) GetHeroVector() float64 {
	if x != nil {
		return x.HeroVector
	}
	return 0
}

func (x *HeroPro) GetAttBehavior() int32 {
	if x != nil {
		return x.AttBehavior
	}
	return 0
}

func (x *HeroPro) GetRunBehavior() int32 {
	if x != nil {
		return x.RunBehavior
	}
	return 0
}

func (x *HeroPro) GetHeroID() int32 {
	if x != nil {
		return x.HeroID
	}
	return 0
}

type CoordPro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *CoordPro) Reset() {
	*x = CoordPro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoordPro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordPro) ProtoMessage() {}

func (x *CoordPro) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordPro.ProtoReflect.Descriptor instead.
func (*CoordPro) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{3}
}

func (x *CoordPro) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CoordPro) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type MapResourcePro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid           int32     `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Id               int32     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` //物品种类
	MapResourceCoord *CoordPro `protobuf:"bytes,3,opt,name=mapResourceCoord,proto3" json:"mapResourceCoord,omitempty"`
}

func (x *MapResourcePro) Reset() {
	*x = MapResourcePro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapResourcePro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapResourcePro) ProtoMessage() {}

func (x *MapResourcePro) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapResourcePro.ProtoReflect.Descriptor instead.
func (*MapResourcePro) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{4}
}

func (x *MapResourcePro) GetRoomid() int32 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *MapResourcePro) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MapResourcePro) GetMapResourceCoord() *CoordPro {
	if x != nil {
		return x.MapResourceCoord
	}
	return nil
}

type PlayerPro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerMsg   *PlayerInfo `protobuf:"bytes,1,opt,name=playerMsg,proto3" json:"playerMsg,omitempty"`
	PlayerCoord *CoordPro   `protobuf:"bytes,2,opt,name=playerCoord,proto3" json:"playerCoord,omitempty"`
	PlayerHero  *HeroPro    `protobuf:"bytes,3,opt,name=playerHero,proto3" json:"playerHero,omitempty"`
}

func (x *PlayerPro) Reset() {
	*x = PlayerPro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerPro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPro) ProtoMessage() {}

func (x *PlayerPro) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPro.ProtoReflect.Descriptor instead.
func (*PlayerPro) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerPro) GetPlayerMsg() *PlayerInfo {
	if x != nil {
		return x.PlayerMsg
	}
	return nil
}

func (x *PlayerPro) GetPlayerCoord() *CoordPro {
	if x != nil {
		return x.PlayerCoord
	}
	return nil
}

func (x *PlayerPro) GetPlayerHero() *HeroPro {
	if x != nil {
		return x.PlayerHero
	}
	return nil
}

//房主可根据自己的Uid更新房间信息。
type PreloadPro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllPlayer      []*PlayerPro      `protobuf:"bytes,2,rep,name=AllPlayer,proto3" json:"AllPlayer,omitempty"`
	AllMapResource []*MapResourcePro `protobuf:"bytes,3,rep,name=AllMapResource,proto3" json:"AllMapResource,omitempty"`
}

func (x *PreloadPro) Reset() {
	*x = PreloadPro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreloadPro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadPro) ProtoMessage() {}

func (x *PreloadPro) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadPro.ProtoReflect.Descriptor instead.
func (*PreloadPro) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{6}
}

func (x *PreloadPro) GetAllPlayer() []*PlayerPro {
	if x != nil {
		return x.AllPlayer
	}
	return nil
}

func (x *PreloadPro) GetAllMapResource() []*MapResourcePro {
	if x != nil {
		return x.AllMapResource
	}
	return nil
}

//玩家初始化UI界面的protobuf
type InitPlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId       int32  `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	HeroLv       int32  `protobuf:"varint,2,opt,name=HeroLv,proto3" json:"HeroLv,omitempty"`
	HeroExp      int32  `protobuf:"varint,3,opt,name=HeroExp,proto3" json:"HeroExp,omitempty"`
	HeroSkill    int32  `protobuf:"varint,4,opt,name=HeroSkill,proto3" json:"HeroSkill,omitempty"`
	WeaponId     int32  `protobuf:"varint,5,opt,name=WeaponId,proto3" json:"WeaponId,omitempty"`
	UserName     string `protobuf:"bytes,6,opt,name=UserName,proto3" json:"UserName,omitempty"`
	AccountLv    int32  `protobuf:"varint,7,opt,name=AccountLv,proto3" json:"AccountLv,omitempty"`
	AccountExp   int32  `protobuf:"varint,8,opt,name=AccountExp,proto3" json:"AccountExp,omitempty"`
	ChooseHeroId int32  `protobuf:"varint,9,opt,name=ChooseHeroId,proto3" json:"ChooseHeroId,omitempty"`
}

func (x *InitPlayerInfo) Reset() {
	*x = InitPlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPlayerInfo) ProtoMessage() {}

func (x *InitPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPlayerInfo.ProtoReflect.Descriptor instead.
func (*InitPlayerInfo) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{7}
}

func (x *InitPlayerInfo) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *InitPlayerInfo) GetHeroLv() int32 {
	if x != nil {
		return x.HeroLv
	}
	return 0
}

func (x *InitPlayerInfo) GetHeroExp() int32 {
	if x != nil {
		return x.HeroExp
	}
	return 0
}

func (x *InitPlayerInfo) GetHeroSkill() int32 {
	if x != nil {
		return x.HeroSkill
	}
	return 0
}

func (x *InitPlayerInfo) GetWeaponId() int32 {
	if x != nil {
		return x.WeaponId
	}
	return 0
}

func (x *InitPlayerInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *InitPlayerInfo) GetAccountLv() int32 {
	if x != nil {
		return x.AccountLv
	}
	return 0
}

func (x *InitPlayerInfo) GetAccountExp() int32 {
	if x != nil {
		return x.AccountExp
	}
	return 0
}

func (x *InitPlayerInfo) GetChooseHeroId() int32 {
	if x != nil {
		return x.ChooseHeroId
	}
	return 0
}

var File_playerinfo_proto protoreflect.FileDescriptor

var file_playerinfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x64, 0x0a, 0x0c,
	0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x0d,
	0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c,
	0x65, 0x6e, 0x22, 0xb1, 0x02, 0x0a, 0x07, 0x48, 0x65, 0x72, 0x6f, 0x50, 0x72, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x72, 0x6f, 0x4c, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65,
	0x72, 0x6f, 0x4c, 0x76, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x48, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x48, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x68, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68,
	0x65, 0x72, 0x6f, 0x41, 0x74, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x53, 0x70,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x53, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x44, 0x65, 0x66, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x44, 0x65, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x65,
	0x72, 0x6f, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a,
	0x68, 0x65, 0x72, 0x6f, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x74,
	0x74, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x41, 0x74, 0x74, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x52, 0x75, 0x6e, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x52, 0x75, 0x6e, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x44, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x48, 0x65, 0x72, 0x6f, 0x49, 0x44, 0x22, 0x26, 0x0a, 0x08, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x50,
	0x72, 0x6f, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x74,
	0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x10, 0x6d, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x50,
	0x72, 0x6f, 0x52, 0x10, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x22, 0x9c, 0x01, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x12, 0x2e, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d,
	0x73, 0x67, 0x12, 0x30, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x12, 0x2d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x65,
	0x72, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x48, 0x65, 0x72, 0x6f, 0x50, 0x72, 0x6f, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48,
	0x65, 0x72, 0x6f, 0x22, 0x79, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72,
	0x6f, 0x12, 0x2d, 0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x52, 0x09, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x3c, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x52, 0x0e,
	0x41, 0x6c, 0x6c, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x92,
	0x02, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x72,
	0x6f, 0x4c, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x72, 0x6f, 0x4c,
	0x76, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x78, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x48,
	0x65, 0x72, 0x6f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x48, 0x65, 0x72, 0x6f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x65, 0x61,
	0x70, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x57, 0x65, 0x61,
	0x70, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x76, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x76, 0x12,
	0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x78, 0x70, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x78, 0x70, 0x12,
	0x22, 0x0a, 0x0c, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x48, 0x65, 0x72,
	0x6f, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_playerinfo_proto_rawDescOnce sync.Once
	file_playerinfo_proto_rawDescData = file_playerinfo_proto_rawDesc
)

func file_playerinfo_proto_rawDescGZIP() []byte {
	file_playerinfo_proto_rawDescOnce.Do(func() {
		file_playerinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_playerinfo_proto_rawDescData)
	})
	return file_playerinfo_proto_rawDescData
}

var file_playerinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_playerinfo_proto_goTypes = []interface{}{
	(*PlayerInfo)(nil),     // 0: Data.PlayerInfo
	(*RoomPlayInfo)(nil),   // 1: Data.RoomPlayInfo
	(*HeroPro)(nil),        // 2: Data.HeroPro
	(*CoordPro)(nil),       // 3: Data.CoordPro
	(*MapResourcePro)(nil), // 4: Data.MapResourcePro
	(*PlayerPro)(nil),      // 5: Data.PlayerPro
	(*PreloadPro)(nil),     // 6: Data.PreloadPro
	(*InitPlayerInfo)(nil), // 7: Data.InitPlayerInfo
}
var file_playerinfo_proto_depIdxs = []int32{
	0, // 0: Data.RoomPlayInfo.AllPlayerInfo:type_name -> Data.PlayerInfo
	3, // 1: Data.MapResourcePro.mapResourceCoord:type_name -> Data.CoordPro
	0, // 2: Data.PlayerPro.playerMsg:type_name -> Data.PlayerInfo
	3, // 3: Data.PlayerPro.playerCoord:type_name -> Data.CoordPro
	2, // 4: Data.PlayerPro.playerHero:type_name -> Data.HeroPro
	5, // 5: Data.PreloadPro.AllPlayer:type_name -> Data.PlayerPro
	4, // 6: Data.PreloadPro.AllMapResource:type_name -> Data.MapResourcePro
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_playerinfo_proto_init() }
func file_playerinfo_proto_init() {
	if File_playerinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_playerinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPlayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroPro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoordPro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapResourcePro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerPro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreloadPro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitPlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playerinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playerinfo_proto_goTypes,
		DependencyIndexes: file_playerinfo_proto_depIdxs,
		MessageInfos:      file_playerinfo_proto_msgTypes,
	}.Build()
	File_playerinfo_proto = out.File
	file_playerinfo_proto_rawDesc = nil
	file_playerinfo_proto_goTypes = nil
	file_playerinfo_proto_depIdxs = nil
}
