// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: rooms.proto

package Data

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RoomPro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Nums   int32 `protobuf:"varint,3,opt,name=nums,proto3" json:"nums,omitempty"`
}

func (x *RoomPro) Reset() {
	*x = RoomPro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rooms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPro) ProtoMessage() {}

func (x *RoomPro) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPro.ProtoReflect.Descriptor instead.
func (*RoomPro) Descriptor() ([]byte, []int) {
	return file_rooms_proto_rawDescGZIP(), []int{0}
}

func (x *RoomPro) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RoomPro) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoomPro) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

type Rooms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Readys  int32      `protobuf:"varint,1,opt,name=readys,proto3" json:"readys,omitempty"`
	Battles int32      `protobuf:"varint,2,opt,name=battles,proto3" json:"battles,omitempty"`
	Overs   int32      `protobuf:"varint,3,opt,name=overs,proto3" json:"overs,omitempty"`
	Room    []*RoomPro `protobuf:"bytes,4,rep,name=room,proto3" json:"room,omitempty"`
}

func (x *Rooms) Reset() {
	*x = Rooms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rooms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rooms) ProtoMessage() {}

func (x *Rooms) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rooms.ProtoReflect.Descriptor instead.
func (*Rooms) Descriptor() ([]byte, []int) {
	return file_rooms_proto_rawDescGZIP(), []int{1}
}

func (x *Rooms) GetReadys() int32 {
	if x != nil {
		return x.Readys
	}
	return 0
}

func (x *Rooms) GetBattles() int32 {
	if x != nil {
		return x.Battles
	}
	return 0
}

func (x *Rooms) GetOvers() int32 {
	if x != nil {
		return x.Overs
	}
	return 0
}

func (x *Rooms) GetRoom() []*RoomPro {
	if x != nil {
		return x.Room
	}
	return nil
}

type RoomChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid   int32  `protobuf:"varint,1,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	Chatdata string `protobuf:"bytes,2,opt,name=chatdata,proto3" json:"chatdata,omitempty"`
}

func (x *RoomChat) Reset() {
	*x = RoomChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rooms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomChat) ProtoMessage() {}

func (x *RoomChat) ProtoReflect() protoreflect.Message {
	mi := &file_rooms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomChat.ProtoReflect.Descriptor instead.
func (*RoomChat) Descriptor() ([]byte, []int) {
	return file_rooms_proto_rawDescGZIP(), []int{2}
}

func (x *RoomChat) GetRoomid() int32 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *RoomChat) GetChatdata() string {
	if x != nil {
		return x.Chatdata
	}
	return ""
}

var File_rooms_proto protoreflect.FileDescriptor

var file_rooms_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x47, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x22, 0x72, 0x0a, 0x05,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x64, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x61, 0x64, 0x79, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x76, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d,
	0x22, 0x3e, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rooms_proto_rawDescOnce sync.Once
	file_rooms_proto_rawDescData = file_rooms_proto_rawDesc
)

func file_rooms_proto_rawDescGZIP() []byte {
	file_rooms_proto_rawDescOnce.Do(func() {
		file_rooms_proto_rawDescData = protoimpl.X.CompressGZIP(file_rooms_proto_rawDescData)
	})
	return file_rooms_proto_rawDescData
}

var file_rooms_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rooms_proto_goTypes = []interface{}{
	(*RoomPro)(nil),  // 0: Data.RoomPro
	(*Rooms)(nil),    // 1: Data.Rooms
	(*RoomChat)(nil), // 2: Data.RoomChat
}
var file_rooms_proto_depIdxs = []int32{
	0, // 0: Data.Rooms.room:type_name -> Data.RoomPro
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rooms_proto_init() }
func file_rooms_proto_init() {
	if File_rooms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rooms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rooms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rooms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rooms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rooms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rooms_proto_goTypes,
		DependencyIndexes: file_rooms_proto_depIdxs,
		MessageInfos:      file_rooms_proto_msgTypes,
	}.Build()
	File_rooms_proto = out.File
	file_rooms_proto_rawDesc = nil
	file_rooms_proto_goTypes = nil
	file_rooms_proto_depIdxs = nil
}
